apiVersion: v1
kind: Service
metadata:
  name: web-elixir-nodeport
  namespace: rocha
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-elixir
    environment: dev