apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim001
  namespace: rocha
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
